### ISSUE TITLE
More issues with workers when the number of colonists go down.

### ISSUE THREAD

**Issue by CarbonIceAlternate** [EpicPuppy613/Colonycraft#21]
**Describe the bug**
If you assign workers to a job, then lose more colonists then you gain, you are told you have something like 100000/20501 workers assigned.

**To Reproduce**
Play the game,
Allow your colony to become dead
Wait for Elders to die
Try to assign

 workers

**Expected behavior**
Workers that die or grow old should be auto unassigned. This is why you have individual colonists. Actually dont, because it was laggy with thousands of not individual colonists

**Additional context**
Oh yeah you can also assign a negative number of workers. This happens.
![Screenshot 2021-10-21 9 41 15 AM](https://user-images.githubusercontent.com/92892191/138321744-571a1e2a-501d-442d-8ff4-02fa82a4bdbc.png)
![Screenshot 2021-10-21 9 42 00 AM](https://user-images.githubusercontent.com/92892191/138321768-a5c4c091-04f5-4441-9810-36c289bd5127.png)
)
![Screenshot 2021-10-21 9 42 20 AM](https://user-images.githubusercontent.com/92892191/138321780-2e5ae628-8474-4b84-b51b-b9212c650b40.png)

**Comment by EpicPuppy613** [comment]
The first issue was already fixed in cdef60a, but hasn't been pushed to the main branch yet. A fix will be implemented for the second issue.
